### ISSUE TITLE
Error a deshabilitar modulo

### ISSUE THREAD

**Issue by jeancarlos110295** [akaunting/module-bc21#1]
Al ejecutar el comando:

php artisan module:disable bc21

la consola me muestra el siguiente error

 Not enough arguments (missing: "company").

**Comment by cuneytsenturk** [comment]
You can not disable this module

**Comment by jeancarlos110295** [comment]
A okay, pero lo raro es que me sale lo mismo si trato de deshabilitar un modulo hecho por mi
